import {apiJson} from '@zag-js/docs';
import {ANATOMY_ICONS} from './anatomy-icons';

interface ApiDetails {
  type: string;
  description: string;
}

interface Details {
  slug: string;
  name: string;
  example: string;
  apiJson?: {[prop: string]: ApiDetails};
  docsPath: string;
  anatomyIcon?: string;
}

export const UTILITIES = [
  {
    slug: 'environment-provider',
    name: 'EnvironmentProvider',
    example: '',
    docsPath: 'src/lib/docs/environment-provider.md',
  },
  {
    slug: 'highlight',
    name: 'Highlight',
    example: '',
    docsPath: 'src/lib/docs/highlight.md',
  },
  {
    slug: 'locale-provider',
    name: 'LocaleProvider',
    example: '',
    docsPath: 'src/lib/docs/locale-provider.md',
  },
  {
    slug: 'portal',
    name: 'Portal',
    example: '',
    docsPath: 'src/lib/docs/portal.md',
  },
  {
    slug: 'presence',
    name: 'Presence',
    example: '',
    docsPath: 'src/lib/docs/presence.md',
    apiJson: apiJson.presence.api,
  },
] satisfies Details[];

export const COMPONENTS = [
  {
    slug: 'accordion',
    name: 'Accordion',
    example: '',
    docsPath: 'src/lib/docs/accordion.md',
    apiJson: apiJson.accordion.api,
    anatomyIcon: ANATOMY_ICONS.accordion,
  },
  {
    slug: 'alert',
    name: 'Alert',
    example: '',
    docsPath: 'src/lib/docs/alert.md',
  },
  {
    slug: 'alert-dialog',
    name: 'AlertDialog',
    example: '',
    docsPath: 'src/lib/docs/alert-dialog.md',
    apiJson: apiJson.dialog.api,
  },
  {
    slug: 'avatar',
    name: 'Avatar',
    example: '',
    docsPath: 'src/lib/docs/avatar.md',
    apiJson: apiJson.avatar.api,
    anatomyIcon: ANATOMY_ICONS.avatar,
  },
  {
    slug: 'breadcrumbs',
    name: 'Breadcrumbs',
    example: '',
    docsPath: 'src/lib/docs/breadcrumbs.md',
  },
  {
    slug: 'carousel',
    name: 'Carousel',
    example: '',
    docsPath: 'src/lib/docs/carousel.md',
    apiJson: apiJson.carousel.api,
    anatomyIcon: ANATOMY_ICONS.carousel,
  },
  {
    slug: 'checkbox',
    name: 'Checkbox',
    example: '',
    docsPath: 'src/lib/docs/checkbox.md',
    apiJson: apiJson.checkbox.api,
    anatomyIcon: ANATOMY_ICONS.checkbox,
  },
  {
    slug: 'clipboard',
    name: 'Clipboard',
    example: '',
    docsPath: 'src/lib/docs/clipboard.md',
    apiJson: apiJson.clipboard.api,
    anatomyIcon: ANATOMY_ICONS.clipboard,
  },
  {
    slug: 'collapsible',
    name: 'Collapsible',
    example: '',
    docsPath: 'src/lib/docs/collapsible.md',
    apiJson: apiJson.collapsible.api,
  },
  {
    slug: 'color-picker',
    name: 'ColorPicker',
    example: '',
    docsPath: 'src/lib/docs/color-picker.md',
    apiJson: apiJson['color-picker'].api,
    anatomyIcon: ANATOMY_ICONS['color-picker'],
  },
  {
    slug: 'combobox',
    name: 'Combobox',
    example: '',
    docsPath: 'src/lib/docs/combobox.md',
    apiJson: apiJson.combobox.api,
    anatomyIcon: ANATOMY_ICONS.combobox,
  },
  {
    slug: 'date-picker',
    name: 'DatePicker',
    example: '',
    docsPath: 'src/lib/docs/date-picker.md',
    apiJson: apiJson['date-picker'].api,
    anatomyIcon: ANATOMY_ICONS['date-picker'],
  },
  {
    slug: 'dialog',
    name: 'Dialog',
    example: '',
    docsPath: 'src/lib/docs/dialog.md',
    apiJson: apiJson.dialog.api,
    anatomyIcon: ANATOMY_ICONS.dialog,
  },
  {
    slug: 'drawer',
    name: 'Drawer',
    example: '',
    docsPath: 'src/lib/docs/drawer.md',
    apiJson: apiJson.dialog.api,
  },
  {
    slug: 'editable',
    name: 'Editable',
    example: '',
    docsPath: 'src/lib/docs/editable.md',
    apiJson: apiJson.editable.api,
    anatomyIcon: ANATOMY_ICONS.editable,
  },
  {
    slug: 'field',
    name: 'Field',
    example: '',
    docsPath: 'src/lib/docs/field.md',
    anatomyIcon: ANATOMY_ICONS.field,
  },
  {
    slug: 'file-upload',
    name: 'FileUpload',
    example: '',
    docsPath: 'src/lib/docs/file-upload.md',
    apiJson: apiJson['file-upload'].api,
    anatomyIcon: ANATOMY_ICONS['file-upload'],
  },
  {
    slug: 'floating-panel',
    name: 'FloatingPanel',
    example: '',
    docsPath: 'src/lib/docs/floating-panel.md',
    apiJson: apiJson['floating-panel'].api,
  },
  {
    slug: 'hover-card',
    name: 'HoverCard',
    example: '',
    docsPath: 'src/lib/docs/hover-card.md',
    apiJson: apiJson['hover-card'].api,
    anatomyIcon: ANATOMY_ICONS['hover-card'],
  },
  {
    slug: 'menu',
    name: 'Menu',
    example: '',
    docsPath: 'src/lib/docs/menu.md',
    apiJson: apiJson.menu.api,
    anatomyIcon: ANATOMY_ICONS.menu,
  },
  {
    slug: 'number-input',
    name: 'NumberInput',
    example: '',
    docsPath: 'src/lib/docs/number-input.md',
    apiJson: apiJson['number-input'].api,
    anatomyIcon: ANATOMY_ICONS['number-input'],
  },
  {
    slug: 'pagination',
    name: 'Pagination',
    example: '',
    docsPath: 'src/lib/docs/pagination.md',
    apiJson: apiJson.pagination.api,
    anatomyIcon: ANATOMY_ICONS.pagination,
  },
  {
    slug: 'pin-input',
    name: 'PinInput',
    example: '',
    docsPath: 'src/lib/docs/pin-input.md',
    apiJson: apiJson['pin-input'].api,
    anatomyIcon: ANATOMY_ICONS['pin-input'],
  },
  {
    slug: 'popover',
    name: 'Popover',
    example: '',
    docsPath: 'src/lib/docs/popover.md',
    apiJson: apiJson.popover.api,
    anatomyIcon: ANATOMY_ICONS.popover,
  },
  {
    slug: 'progress-linear',
    name: 'Progress - Linear',
    example: '',
    docsPath: 'src/lib/docs/progress.md',
    apiJson: apiJson.progress.api,
    anatomyIcon: ANATOMY_ICONS['linear-progress'],
  },
  {
    slug: 'progress-circular',
    name: 'Progress - Circular',
    example: '',
    docsPath: 'src/lib/docs/progress.md',
    apiJson: apiJson.progress.api,
    anatomyIcon: ANATOMY_ICONS['circular-progress'],
  },
  {
    slug: 'qr-code',
    name: 'QrCode',
    example: '',
    docsPath: 'src/lib/docs/qr-code.md',
    apiJson: apiJson['qr-code'].api,
    anatomyIcon: ANATOMY_ICONS['qr-code'],
  },
  {
    slug: 'radio-group',
    name: 'RadioGroup',
    example: '',
    docsPath: 'src/lib/docs/radio-group.md',
    apiJson: apiJson['radio-group'].api,
    anatomyIcon: ANATOMY_ICONS['radio-group'],
  },
  {
    slug: 'rating-group',
    name: 'RatingGroup',
    example: '',
    docsPath: 'src/lib/docs/rating-group.md',
    apiJson: apiJson['rating-group'].api,
    anatomyIcon: ANATOMY_ICONS['rating-group'],
  },
  {
    slug: 'segment-group',
    name: 'SegmentGroup',
    example: '',
    docsPath: 'src/lib/docs/segment-group.md',
    apiJson: apiJson['radio-group'].api,
    anatomyIcon: ANATOMY_ICONS['segmented-control'],
  },
  {
    slug: 'select',
    name: 'Select',
    example: '',
    docsPath: 'src/lib/docs/select.md',
    apiJson: apiJson.select.api,
  },
  {
    slug: 'signature-pad',
    name: 'SignaturePad',
    example: '',
    docsPath: 'src/lib/docs/signature-pad.md',
    apiJson: apiJson['signature-pad'].api,
    anatomyIcon: ANATOMY_ICONS['signature-pad'],
  },
  {
    slug: 'slider',
    name: 'Slider',
    example: '',
    docsPath: 'src/lib/docs/slider.md',
    apiJson: apiJson.slider.api,
    anatomyIcon: ANATOMY_ICONS.slider,
  },
  {
    slug: 'splitter',
    name: 'Splitter',
    example: '',
    docsPath: 'src/lib/docs/splitter.md',
    apiJson: apiJson.splitter.api,
    anatomyIcon: ANATOMY_ICONS.splitter,
  },
  {
    slug: 'steps',
    name: 'Steps',
    example: '',
    docsPath: 'src/lib/docs/steps.md',
    apiJson: apiJson.steps.api,
    anatomyIcon: ANATOMY_ICONS.steps,
  },
  {
    slug: 'switch',
    name: 'Switch',
    example: '',
    docsPath: 'src/lib/docs/switch.md',
    apiJson: apiJson.switch.api,
    anatomyIcon: ANATOMY_ICONS.switch,
  },
  {
    slug: 'tabs',
    name: 'Tabs',
    example: '',
    docsPath: 'src/lib/docs/tabs.md',
    apiJson: apiJson.tabs.api,
    anatomyIcon: ANATOMY_ICONS.tabs,
  },
  {
    slug: 'tags-input',
    name: 'TagsInput',
    example: '',
    docsPath: 'src/lib/docs/tags-input.md',
    apiJson: apiJson['tags-input'].api,
    anatomyIcon: ANATOMY_ICONS['tags-input'],
  },
  {
    slug: 'time-picker',
    name: 'TimePicker',
    example: '',
    docsPath: 'src/lib/docs/time-picker.md',
    apiJson: apiJson['time-picker'].api,
    anatomyIcon: ANATOMY_ICONS['time-picker'],
  },
  {
    slug: 'timer',
    name: 'Timer',
    example: '',
    docsPath: 'src/lib/docs/timer.md',
    apiJson: apiJson.timer.api,
  },
  {
    slug: 'toast',
    name: 'Toast',
    example: '',
    docsPath: 'src/lib/docs/toast.md',
    apiJson: apiJson.toast.api,
    anatomyIcon: ANATOMY_ICONS.toast,
  },
  {
    slug: 'toggle',
    name: 'Toggle',
    example: '',
    docsPath: 'src/lib/docs/toggle.md',
  },
  {
    slug: 'toggle-group',
    name: 'ToggleGroup',
    example: '',
    docsPath: 'src/lib/docs/toggle-group.md',
    apiJson: apiJson['toggle-group'].api,
    anatomyIcon: ANATOMY_ICONS['toggle-group'],
  },
  {
    slug: 'tooltip',
    name: 'Tooltip',
    example: '',
    docsPath: 'src/lib/docs/tooltip.md',
    apiJson: apiJson.tooltip.api,
    anatomyIcon: ANATOMY_ICONS.tooltip,
  },
  {
    slug: 'tree-view',
    name: 'TreeView',
    example: '',
    docsPath: 'src/lib/docs/tree-view.md',
    apiJson: apiJson['tree-view'].api,
    anatomyIcon: ANATOMY_ICONS['tree-view'],
  },
] satisfies Details[];
